export const iconsList = [
    'UtensilsCrossed',
    'Briefcase',
    'BriefcaseBusiness',
    'GraduationCap',
    'Heart',
    'Dumbbell',
    'Music2',
    'CalendarCheck',
    'Clapperboard',
    'Home',
    'UserRound',
    'Users',
    'Gamepad2',
    'PenTool',
    'CheckSquare',
    'Plane',
    'BookOpen',
    'Wallet',
    'NotebookPen',
    'CalendarDays',
    'Code',
    'ShoppingCart',
    'Lightbulb'
] as const;
