export const task = [
    { "id": "1", "name": "Ler um livro", "category": "Pessoal", "priority": "Alta", "date": "19/02/2025", "active": false },
    { "id": "2", "name": "Revisar relatório", "category": "Trabalho", "priority": "Média", "date": "19/02/2025", "active": true },
    { "id": "3", "name": "Estudar React", "category": "Estudo", "priority": "Alta", "date": "19/02/2025", "active": false },
    { "id": "4", "name": "Treinar na academia", "category": "Pessoal", "priority": "Média", "date": "19/02/2025", "active": false },
    { "id": "5", "name": "Reunião com equipe", "category": "Trabalho", "priority": "Alta", "date": "19/02/2025", "active": false },
    { "id": "6", "name": "Estudar algoritmos", "category": "Estudo", "priority": "Baixa", "date": "19/02/2025", "active": true },
    { "id": "7", "name": "Meditar", "category": "Pessoal", "priority": "Média", "date": "19/02/2025", "active": false },
    { "id": "8", "name": "Enviar e-mails", "category": "Trabalho", "priority": "Baixa", "date": "19/02/2025", "active": false },
    { "id": "9", "name": "Fazer resumo de aula", "category": "Estudo", "priority": "Média", "date": "19/02/2025", "active": false },
    { "id": "10", "name": "Passear com o cachorro", "category": "Pessoal", "priority": "Baixa", "date": "19/02/2025", "active": false },

    { "id": "11", "name": "Fazer compras", "category": "Pessoal", "priority": "Média", "date": "20/02/2025", "active": false },
    { "id": "12", "name": "Atualizar planilhas", "category": "Trabalho", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "13", "name": "Assistir aula online", "category": "Estudo", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "14", "name": "Correr no parque", "category": "Pessoal", "priority": "Baixa", "date": "20/02/2025", "active": false },
    { "id": "15", "name": "Reunião com cliente", "category": "Trabalho", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "16", "name": "Estudar Next.js", "category": "Estudo", "priority": "Média", "date": "20/02/2025", "active": false },
    { "id": "17", "name": "Fazer terapia", "category": "Pessoal", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "18", "name": "Organizar documentos", "category": "Trabalho", "priority": "Média", "date": "20/02/2025", "active": false },
    { "id": "19", "name": "Fazer exercício prático", "category": "Estudo", "priority": "Baixa", "date": "20/02/2025", "active": false },
    { "id": "20", "name": "Sair com amigos", "category": "Pessoal", "priority": "Média", "date": "20/02/2025", "active": false },

    { "id": "21", "name": "Fazer planejamento semanal", "category": "Trabalho", "priority": "Alta", "date": "21/02/2025", "active": false },
    { "id": "22", "name": "Fazer revisão de código", "category": "Estudo", "priority": "Média", "date": "21/02/2025", "active": false },
    { "id": "23", "name": "Limpar a casa", "category": "Pessoal", "priority": "Alta", "date": "21/02/2025", "active": false },
    { "id": "24", "name": "Apresentação para diretoria", "category": "Trabalho", "priority": "Alta", "date": "21/02/2025", "active": true },
    { "id": "25", "name": "Revisar conteúdos de lógica", "category": "Estudo", "priority": "Baixa", "date": "21/02/2025", "active": false },
    { "id": "26", "name": "Fazer caminhada", "category": "Pessoal", "priority": "Média", "date": "21/02/2025", "active": true },
    { "id": "27", "name": "Finalizar relatório", "category": "Trabalho", "priority": "Média", "date": "21/02/2025", "active": false },
    { "id": "28", "name": "Resolver desafios de programação", "category": "Estudo", "priority": "Alta", "date": "21/02/2025", "active": true },
    { "id": "29", "name": "Lavar o carro", "category": "Pessoal", "priority": "Baixa", "date": "21/02/2025", "active": false },
    { "id": "30", "name": "Participar de webinar", "category": "Trabalho", "priority": "Média", "date": "21/02/2025", "active": true },

    { "id": "31", "name": "Fazer alongamento", "category": "Pessoal", "priority": "Baixa", "date": "22/02/2025", "active": false },
    { "id": "32", "name": "Redigir artigo técnico", "category": "Trabalho", "priority": "Alta", "date": "22/02/2025", "active": true },
    { "id": "33", "name": "Estudar design patterns", "category": "Estudo", "priority": "Média", "date": "22/02/2025", "active": false },
    { "id": "34", "name": "Fazer compras", "category": "Pessoal", "priority": "Alta", "date": "22/02/2025", "active": true },
    { "id": "35", "name": "Atualizar projetos", "category": "Trabalho", "priority": "Média", "date": "22/02/2025", "active": false },
    { "id": "36", "name": "Praticar inglês", "category": "Estudo", "priority": "Alta", "date": "22/02/2025", "active": true },
    { "id": "37", "name": "Cuidar das plantas", "category": "Pessoal", "priority": "Baixa", "date": "22/02/2025", "active": false },
    { "id": "38", "name": "Enviar relatórios", "category": "Trabalho", "priority": "Alta", "date": "22/02/2025", "active": true },
    { "id": "39", "name": "Estudar novas tecnologias", "category": "Estudo", "priority": "Média", "date": "22/02/2025", "active": false },
    { "id": "40", "name": "Cozinhar algo novo", "category": "Pessoal", "priority": "Média", "date": "22/02/2025", "active": true },

    { "id": "41", "name": "Fazer alongamento", "category": "Pessoal", "priority": "Baixa", "date": "23/02/2025", "active": false },
    { "id": "42", "name": "Redigir artigo técnico", "category": "Trabalho", "priority": "Alta", "date": "23/02/2025", "active": true },
    { "id": "43", "name": "Estudar design patterns", "category": "Estudo", "priority": "Média", "date": "23/02/2025", "active": false },
    { "id": "44", "name": "Fazer compras", "category": "Pessoal", "priority": "Alta", "date": "23/02/2025", "active": true },
    { "id": "45", "name": "Atualizar projetos", "category": "Trabalho", "priority": "Média", "date": "23/02/2025", "active": false },
    { "id": "46", "name": "Praticar inglês", "category": "Estudo", "priority": "Alta", "date": "23/02/2025", "active": true },
    { "id": "47", "name": "Cuidar das plantas", "category": "Pessoal", "priority": "Baixa", "date": "23/02/2025", "active": false },
    { "id": "48", "name": "Enviar relatórios", "category": "Trabalho", "priority": "Alta", "date": "23/02/2025", "active": true },
    { "id": "49", "name": "Estudar novas tecnologias", "category": "Estudo", "priority": "Média", "date": "23/02/2025", "active": false },
    { "id": "50", "name": "Cozinhar algo novo", "category": "Pessoal", "priority": "Média", "date": "23/02/2025", "active": true },

    { "id": "51", "name": "Ler artigo técnico", "category": "Estudo", "priority": "Média", "date": "19/02/2025", "active": false },
    { "id": "52", "name": "Planejar metas mensais", "category": "Pessoal", "priority": "Alta", "date": "19/02/2025", "active": false },
    { "id": "53", "name": "Revisar código de projeto", "category": "Trabalho", "priority": "Média", "date": "19/02/2025", "active": false },
    { "id": "54", "name": "Estudar SQL", "category": "Estudo", "priority": "Alta", "date": "19/02/2025", "active": false },
    { "id": "55", "name": "Fazer check-up médico", "category": "Pessoal", "priority": "Média", "date": "19/02/2025", "active": false },
    { "id": "56", "name": "Reunião de feedback com chefe", "category": "Trabalho", "priority": "Alta", "date": "19/02/2025", "active": false },
    { "id": "57", "name": "Estudar Git", "category": "Estudo", "priority": "Média", "date": "19/02/2025", "active": false },
    { "id": "58", "name": "Fazer exercícios de lógica", "category": "Estudo", "priority": "Alta", "date": "19/02/2025", "active": false },
    { "id": "59", "name": "Fazer planejamento de viagem", "category": "Pessoal", "priority": "Baixa", "date": "19/02/2025", "active": false },
    { "id": "60", "name": "Revisar apresentações", "category": "Trabalho", "priority": "Média", "date": "19/02/2025", "active": false },

    { "id": "61", "name": "Fazer revisão de código", "category": "Estudo", "priority": "Média", "date": "20/02/2025", "active": false },
    { "id": "62", "name": "Revisar metas semanais", "category": "Pessoal", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "63", "name": "Testar nova funcionalidade", "category": "Trabalho", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "64", "name": "Estudar Node.js", "category": "Estudo", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "65", "name": "Ler livro de desenvolvimento pessoal", "category": "Pessoal", "priority": "Média", "date": "20/02/2025", "active": false },
    { "id": "66", "name": "Finalizar projeto de trabalho", "category": "Trabalho", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "67", "name": "Praticar exercícios físicos", "category": "Pessoal", "priority": "Baixa", "date": "20/02/2025", "active": false },
    { "id": "68", "name": "Estudar programação orientada a objetos", "category": "Estudo", "priority": "Alta", "date": "20/02/2025", "active": false },
    { "id": "69", "name": "Participar de encontro de networking", "category": "Trabalho", "priority": "Média", "date": "20/02/2025", "active": false },
    { "id": "70", "name": "Revisar contrato", "category": "Trabalho", "priority": "Média", "date": "20/02/2025", "active": false },

    { "id": "71", "name": "Organizar espaço de trabalho", "category": "Pessoal", "priority": "Alta", "date": "21/02/2025", "active": false },
    { "id": "72", "name": "Escrever código para novo projeto", "category": "Trabalho", "priority": "Alta", "date": "21/02/2025", "active": false },
    { "id": "73", "name": "Estudar lógica de programação", "category": "Estudo", "priority": "Alta", "date": "21/02/2025", "active": false },
    { "id": "74", "name": "Analisar dados do projeto", "category": "Trabalho", "priority": "Média", "date": "21/02/2025", "active": false },
    { "id": "75", "name": "Ler livro de ficção científica", "category": "Pessoal", "priority": "Média", "date": "21/02/2025", "active": false },
    { "id": "76", "name": "Estudar React Native", "category": "Estudo", "priority": "Alta", "date": "21/02/2025", "active": false },
    { "id": "77", "name": "Fazer revisão de performance", "category": "Trabalho", "priority": "Média", "date": "21/02/2025", "active": false },
    { "id": "78", "name": "Praticar meditação", "category": "Pessoal", "priority": "Baixa", "date": "21/02/2025", "active": false },
    { "id": "79", "name": "Estudar design de interfaces", "category": "Estudo", "priority": "Média", "date": "21/02/2025", "active": false },
    { "id": "80", "name": "Fazer relatório de resultados", "category": "Trabalho", "priority": "Média", "date": "21/02/2025", "active": false },

    { "id": "81", "name": "Limpar o quarto", "category": "Pessoal", "priority": "Baixa", "date": "22/02/2025", "active": false },
    { "id": "82", "name": "Revisar performance do sistema", "category": "Trabalho", "priority": "Alta", "date": "22/02/2025", "active": false },
    { "id": "83", "name": "Estudar TypeScript", "category": "Estudo", "priority": "Alta", "date": "22/02/2025", "active": false },
    { "id": "84", "name": "Organizar e-mails", "category": "Pessoal", "priority": "Média", "date": "22/02/2025", "active": false },
    { "id": "85", "name": "Fazer curso online de design", "category": "Estudo", "priority": "Média", "date": "22/02/2025", "active": false },
    { "id": "86", "name": "Estudar Cloud Computing", "category": "Estudo", "priority": "Alta", "date": "22/02/2025", "active": false },
    { "id": "87", "name": "Participar de evento de tecnologia", "category": "Trabalho", "priority": "Baixa", "date": "22/02/2025", "active": false },
    { "id": "88", "name": "Revisar conteúdo de curso", "category": "Estudo", "priority": "Média", "date": "22/02/2025", "active": false },
    { "id": "89", "name": "Criar portfólio online", "category": "Trabalho", "priority": "Alta", "date": "22/02/2025", "active": false },
    { "id": "90", "name": "Fazer manutenção no site", "category": "Trabalho", "priority": "Média", "date": "22/02/2025", "active": false }


]

